packages:
  # Main packages
  - packages/compiler
  - packages/runtime
  # Build plugins
  - packages/esbuild-plugin
  # Visual Studio Code
  - packages/vscode-extension
  # Playground
  - playground
